---
title: "Workshop Group 31/1 Project"
output: html_document
author: "Ryan Hall, Eddie Washbrook, Eric Rogers, (add name here)"
date: "2022-11-16"
---
# Do geographical location and characteristics have an effect on internet quality of life in the UK? An analysis of and comparison between two months in 2019

### Load required packages

```{r load-packages, message = FALSE, warning = FALSE}
library(tidyverse)
library(tidymodels)
library(janitor)
library(geojsonio)
```

### Read in data from csv files

```{r load-data, message = FALSE}

feb_2019 <- read.csv("data/broadband_data_february_2019.csv")
aug_2019 <- read.csv("data/broadband_data_august_2019.csv")
gdhi_region <- read.csv("data/gdhi_per_region.csv", skip = 1)

```

### Tidy the datasets to make them easier to use

```{r clean-data}
feb_2019 <- feb_2019 %>%
  clean_names() %>%
  select(-ofcom_product) %>%    # These steps are to make the columns match the August dataset.
  rename("distance_from_exchange" = "distance_from_exchange_band")
  
aug_2019 <- aug_2019 %>%
  clean_names()

regions <- c("United Kingdom", "England", "North East", "North West", "Yorkshire & Humber", "East Midlands", 
             "West Midlands", "East", "London", "South East", "South West", "Wales", "Scotland", "Northern Ireland")

gdhi_region <- gdhi_region %>%
  clean_names() %>%
  drop_na() %>%
  rename("region" = "countries_and_regions_of_the_uk") %>%
  mutate(region = regions,
         gdhi_per_head = str_remove_all(gdhi_per_head, ","),
         gdhi_per_head = as.numeric(gdhi_per_head)
         )

```

```{r maps}
region_map <- geojson_read("uk_regions.geojson")
```

# Houshold Income vs 24 hour Download Speed
```{r income-24h_download}
feb_gdhi_join <- left_join(feb_2019, gdhi_region , by = "region")
feb_reg_gdhi_fit <- linear_reg() %>%
  set_engine("lm") %>%
  fit(x24_hr_average_download_speed ~ gdhi_per_head, data= feb_gdhi_join) %>%
  tidy()
feb_reg_gdhi_fit
  
```
