---
title: Geographical Location and Internet Quality of Life
author: by Workshop Group 31/1
output: html_document
---

## Research Question

Our research question is the following: "Do geographical location and characteristics have an effect on internet quality of life in the UK?". 

Internet quality of life is becoming more important than ever - especially with how increasingly online our world is becoming. We aim to examine the relationships between geographical location of UK internet users (and related metrics such as household income) and metrics which can help us gain a picture of internet quality of life, such as download speed. We will also consider how things have changed over the course of two months at different points in the year.

## Data

Briefly describe your dataset here - include a description of the key variables you will be investigating. 
Include a citation for your data. 
See http://libraryguides.vu.edu.au/c.php?g=386501&p=4347840 for guidance on proper citation for datasets. 
If you got your data off the web, make sure to note the retrieval date.

For our project we used 3 datasets in total, 2 from data.gov.ukm, and one from ons.gov.uk. The first two datasets concern fixed line broadband speeds in the UK in February and August 2019, respectively. Both datasets come from Ofcom, the UK's communications regulator. The broadband data was collected from a sample of customers who had speed monitoring equipment stored in their homes.

The third data contains information on the GDHI (Gross Disposable Household Income) for UK consituent countries and regions.

For the purposes of our project, we will be mainly focusing on 24 hour average download speed, Urban/Rural (whether or not a reading comes from an urban or rural location) and GDHI per head.

## Findings

comparison of feb and aug -> improvement in internet quality
linear model: urbanrural/region/ghdi -> effect ads/jitter/packet loss
prediction: p-value of ads
assumptions: 
limitations: 
ideas for future work:



```{r load-data, echo = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)
library(tidymodels)
library(janitor)
library(geojsonio)
library(ggplot2)
library(dplyr)

feb_2019 <- read.csv("data/broadband_data_february_2019.csv")
aug_2019 <- read.csv("data/broadband_data_august_2019.csv")
gdhi_region <- read.csv("data/gdhi_per_region.csv", skip = 1)

feb_2019 <- feb_2019 %>%
  clean_names() %>%
  select(-ofcom_product) %>%    # These steps are to make the columns match the August dataset.
  rename("distance_from_exchange" = "distance_from_exchange_band")
  
aug_2019 <- aug_2019 %>%
  clean_names()

regions <- c("United Kingdom", "England", "North East", "North West", "Yorkshire & Humber", "East Midlands", 
             "West Midlands", "East", "London", "South East", "South West", "Wales", "Scotland", "Northern Ireland")

gdhi_region <- gdhi_region %>%
  clean_names() %>%
  drop_na() %>%
  rename("region" = "countries_and_regions_of_the_uk") %>%
  mutate(region = regions,
         gdhi_per_head = str_remove_all(gdhi_per_head, ","),
         gdhi_per_head = as.numeric(gdhi_per_head)
         )

aug_2019_month <- aug_2019 %>%
  mutate(month = "August")

all_2019 <- feb_2019 %>%
  mutate(month = "February") %>%
  rbind(aug_2019_month)

# Join datasets with gdhi_region set
feb_gdhi_join <- left_join(feb_2019, gdhi_region , by = "region")
aug_gdhi_join <- left_join(aug_2019, gdhi_region , by = "region")
all_gdhi_join <- left_join(all_2019, gdhi_region , by = "region")
```

## Presentation

Our presentation can be found [here](presentation/presentation.html).


## References

### Data sources:

https://www.data.gov.uk/dataset/dfe843da-06ca-4680-9ba0-fbb27319e402/uk-fixed-line-broadband-performance

https://www.ons.gov.uk/economy/regionalaccounts/grossdisposablehouseholdincome/bulletins/regionalgrossdisposablehouseholdincomegdhi/1997to2019

### References for maps:

https://www.r-graph-gallery.com 

https://www.kaggle.com/datasets/dorianlazar/uk-regions-geojson

https://cran.r-project.org/web/packages/geojsonio/geojsonio.pdf 

https://www.rdocumentation.org/packages/graphics/versions/3.6.2/topics/plot 

https://rdrr.io/cran/tigris/man/geo_join.html 

